[FIX] OD-1476: exclude all picking lines when freeing reservations
VanMoof/stock-logistics-workflow pull request #13
Opened 2021-10-06 14:01 UTC by hbrunn

I propose to add this to our feature branch and then bump the hash there.

Shouldn't we PR this whole branch into OCA too?

Buildout PR: https://github.com/VanMoof/odoo-buildout/pull/296

2021-10-06 14:02 UTC, hbrunn commented on stock_move_manual_lot/models/stock_move_line.py
> +                    ml_to_ignore=self.mapped('picking_id.move_line_ids'),
we need this because this function isn't called on all move lines at once, and we actually don't want this function to mess with lines from our own picking(s) anyways.

The problematic line is https://github.com/OCA/OCB/blob/12.0/addons/stock/models/stock_move_line.py#L526

2021-10-06 14:09 UTC, astirpe approved these changes
Works fine now! :+1:

2021-10-08 09:39 UTC, StefanRijnhart requested changes
~~This PR does not add a test to reproduce the problem it tries to solve, and it introduces a regression in the case multiple move lines of the same picking are updated, breaking test 03.~~ Comments addressed :sun_with_face:

2021-10-08 10:04 UTC, StefanRijnhart commented on stock_move_manual_lot/models/stock_picking.py
> +        return super(StockPicking, self).write(vals)
Here too, the fact that the previous version worked is witnessed by the tests that were added at that time. If this does fix a problem, please add a test to reproduce it.

2021-10-08 17:14 UTC, hbrunn commented
now with a different approach and tests

2021-10-08 18:09 UTC, StefanRijnhart commented
Looking good! As it happens, I was working on the same issue and I'm proposing a complementary part of the solution into this branch here: https://github.com/VanMoof/stock-logistics-workflow/pull/15

2021-10-09 02:59 UTC, hbrunn commented
...and another rewrite. please re-review

2021-10-09 08:09 UTC, StefanRijnhart commented
Excellent improvement.

Waiting on your review of my PR into this one before my approval.

2021-10-09 08:26 UTC, hbrunn commented
thanks, now we're there I think

2021-10-09 11:20 UTC, StefanRijnhart approved these changes
I've restarted tests on the buildout branch as the final validation

2021-10-19 13:47 UTC, merged