[FIX] Don't throw 'unreserve more than in stock' error when creating backorder
VanMoof/stock-logistics-workflow pull request #7
Opened 2021-09-10 13:57 UTC by StefanRijnhart

2021-09-13 08:17 UTC, astirpe approved these changes

2021-09-14 10:18 UTC, hbrunn requested changes

2021-09-14 10:18 UTC, hbrunn commented on stock_move_manual_lot/models/stock_move_line.py
> +                return
```suggestion
                continue
```

2021-09-14 10:47 UTC, StefanRijnhart commented on stock_move_manual_lot/models/stock_move_line.py
> +                return
Thanks! Can you apply the fix yourself?

2021-09-14 10:48 UTC, StefanRijnhart commented on stock_move_manual_lot/models/stock_move_line.py
> +                return
Oh I can just press commit.

2021-09-14 10:53 UTC, hbrunn approved these changes

2021-09-14 14:09 UTC, pankk approved these changes

2021-09-15 07:47 UTC, dkubiak789 approved these changes

2021-09-21 10:37 UTC, merged